if: branch IN (alpha, beta, master)

language: shell
os: windows

script:
- if [[ $TRAVIS_BRANCH = "master" ]] ; then
        dotnet pack -c Release /property:Version=0.3.$TRAVIS_BUILD_NUMBER;
        dotnet nuget push ./EPPlus.Html/bin/Release/EPPlus.Html.0.3.$TRAVIS_BUILD_NUMBER.nupkg -s https://www.myget.org/F/fitogram/auth/085eb83a-9100-4b7d-8748-fcb7182d5111/api/v3/index.json;
    else
        dotnet pack -c Release /property:Version=0.3.$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH;
        dotnet nuget push ./EPPlus.Html/bin/Release/EPPlus.Html.0.3.$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH.nupkg -s https://www.myget.org/F/fitogram/auth/085eb83a-9100-4b7d-8748-fcb7182d5111/api/v3/index.json;
    fi

after_success:
- echo "Tadaaaaaa :)"